# Generated by Django 5.2.6 on 2025-09-16 01:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=220, unique=True)),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('publicado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-publicado_en'],
                'indexes': [models.Index(fields=['slug'], name='blog_public_slug_01a6a4_idx'), models.Index(fields=['creado_en'], name='blog_public_creado__b84023_idx')],
            },
        ),
    ]
