# Generated by Django 5.2.6 on 2025-09-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cosa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cosa',
        ),
    ]
